### ISSUE TITLE
cannot use pos_list keyword argument in Pore.attach

### ISSUE THREAD

**Issue by davidemarchiUPO** [Ajax23/PoreMS#23]
whenever i try to use the pos_list keyword, i get the error:

> TypeError: attach() got an unexpected keyword argument 'pos_list'

as if this keyword is not actually implemented in the package.

**Comment by Ajax23** [comment]
Could you post the code that reproduces the error?

**Comment by davidemarchiUPO** [comment]
sure. here is the script and the .mol2 file used in the script.

i'm not sure i'm using the pos_list keyword in the correct way, but in any case it seems it is not even recognized by the attach() method.

[poslist_problem.zip](https://github.com/Ajax23/PoreMS/files/6716180/poslist_problem.zip)

**Comment by Ajax23** [comment]
Thank you.

As a note, you are using the attach function of the System classes, not the pore class. In the first iterations of the code, we decided, o leave the position variable out since multiple input types are possible (molar, percentage). But I suppose if one is planning to define specific positions this should not be an issue. 

I added the pos_list variable to the attach function in the newest commit [9fabe99](https://github.com/Ajax23/PoreMS/commit/9fabe9918bb67960719a0b60fff5a7b5b6ba7c11). So please install the current version of the master branch. 

pip install git+https://github.com/ajax23/porems.git#egg=porems

One more question: If you plan on using flat surfaces, we could add these as separate functions instead of using a cheat version of a cylindrical pore with a zero diameter (if you are interested in that feature, please open a separate issue).
